#!/bin/bash
#-----
# Remove all artifacts generated by previous runs
#-----
if [ -f urls.txt ]
then
  rm urls.txt
fi
if [ -f urls_raw.txt ]
then
  rm urls_raw.txt
fi
rm c*.txt
if [ -f queryfile.sql ]
then
  rm queryfile.sql
fi
if [ -f results.db ]
then
  rm results.db
fi
if [ -f averages.csv ]
then
  rm averages.csv
fi
if [ -f errorrate.csv ]
then
  rm errorrate.csv
fi
if [ -f fit.log ]
then
  rm fit.log
fi

